apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
  namespace: egs-fuellink
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 9000
  selector:
    io.kompose.service: kafdrop
status:
  loadBalancer: {}
