apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-plate-recognizer-stream
  name: kafka-plate-recognizer-stream
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-plate-recognizer-stream
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-plate-recognizer-stream
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo Waiting for Kafka to be ready... && cub kafka-ready -b kafka:29092
          1 20 && sh check_topics.sh && mvn exec:java -Dexec.mainClass=applications.PlateRecognizer
        env:
        - name: KAFKA_BROKER_ID
          value: ignored
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: ignored
        image: registry.deti/egs-fuellink/plate-recognizer_stream:1.0
        imagePullPolicy: ""
        name: kafka-plate-recognizer-stream
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
